services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword  # Change in production!
    networks:
    - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI (optional)
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork: